# list tag: gcloud container images list-tags gcr.io/kaggle-images/python
FROM gcr.io/kaggle-images/python:v56

# Install useful libraries
RUN pip install -U pip && \
    pip install japanize-matplotlib
